# sonar.projectKey=
# sonar.projectName=2401020_Restaurant_project
# sonar.projectVersion=1.0

# # Source folders
# sonar.sources=backend,frontend

# # Exclude unnecessary folders
# sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# # Language & encoding
# sonar.language=js
# sonar.sourceEncoding=UTF-8

# # SonarQube server
# sonar.host.url=http://localhost:9000

# # Authentication token
# sonar.login=sqp_f8cd5c161d5a700e8a45c67ffbb3bd46362f902f

sonar.projectKey=2401020_Restaurant_project
sonar.projectName=2401020_Restaurant_project
sonar.sources=frontend,backend
sonar.sourceEncoding=UTF-8
