# sonar.projectKey=2401020_Restaurant_Reservation
# sonar.projectName=2401020_Restaurant_Reservation
# sonar.projectVersion=1.0
# sonar.sources=backend,frontend
# sonar.exclusions=**/node_modules/**
# sonar.sourceEncoding=UTF-8
# sonar.host.url=http://sonarqube.imcc.com/
# # http://localhost:9000
# sonar.login=sqp_ef7a0be9b9821ae2b4f29a64fb8b1fc505932a05
# # squ_1cd7365e7df1db533467f18570d86ec11e208993
# sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.projectKey=2401020_Restaurant_Reservation
sonar.projectName=2401020_Restaurant_Reservation
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://my-sonarqube-sonarqube.sonarqube.svc.cluster.local:9000
# sonar.login removed, use SONAR_TOKEN from Jenkins instead
sonar.javascript.lcov.reportPaths=coverage/lcov.info
