apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "2401020"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/my-repository/mern-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
