apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: "2401020"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: nexus.imcc.com:8085/my-repository/mern-frontend:latest
          ports:
            - containerPort: 80
